import { Lora, Raleway, Space_Mono } from "next/font/google";
import "./globals.css";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const space = Space_Mono({
  weight: "400",
  variable: "--font-space",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="reflact" className="scroll-smooth">
      <body
        className={`${lora.variable} ${raleway.variable} ${space.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
